<a href="https://colab.research.google.com/github/Maksym17V2/Machin--learning-bootcamp/blob/main/BrakiDanych.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Bibliotek

In [1]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'1.6.1'

# Wygenerowanie danych

In [2]:

data = {
    'size': ['XL', 'L', 'M', np.nan, 'M', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red', 'green'],
    'gender': ['female', 'male', np.nan, 'female', 'female', 'male'],
    'price': [199.0, 89.0, np.nan, 129.0, 79.0, 89.0],
    'weight': [500, 450, 300, np.nan, 410, np.nan],
    'bought': ['yes', 'no', 'yes', 'no', 'yes', 'no']
}

df_raw = pd.DataFrame(data=data)
df_raw

  size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green  female  129.0     NaN     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0     NaN     no

# Utworzenie kopii danych

In [3]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   size    5 non-null      object
 1   color   6 non-null      object
 2   gender  5 non-null      object
 3   price   5 non-null      float64
 4   weight  4 non-null      float64
 5   bought  6 non-null      object
dtypes: float64(2), object(4)
memory usage: 420.0+ bytes

# Sprawdzenie braków

In [4]:
df.isnull()

    size  color  gender  price  weight  bought
0  False  False   False  False   False   False
1  False  False   False  False   False   False
2  False  False    True   True   False   False
3   True  False   False  False    True   False
4  False  False   False  False   False   False
5  False  False   False  False    True   False

In [6]:
df.isnull().sum()

size      1
color     0
gender    1
price     1
weight    2
bought    0
dtype: int64

In [8]:
df.isnull().sum().sum()

np.int64(5)

In [10]:
df.isnull().sum() / len(df)

size      0.166667
color     0.000000
gender    0.166667
price     0.166667
weight    0.333333
bought    0.000000
dtype: float64